apiVersion: v1
kind: Service
metadata:
  name: apm-service
  namespace: "apm"
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: apm-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-configmap
  namespace: apm
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      rum:
        enabled: true
    apm-server.kibana:
      host: "kibana-service:5601"
      protocol: "http"
      enabled: true
      username: "elastic"
      password: "smartlogsvn"
    output.elasticsearch:
      hosts: ["els-service:9200"]
      username: "elastic"
      password: "smartlogsvn"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: "apm"
  labels:
    app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-southeast-1a
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:7.15.2
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: apm-config
              mountPath: /usr/share/apm-server/apm-server.yml
              readOnly: true
              subPath: apm-server.yml
      volumes:
        - name: apm-config
          configMap:
            name: apm-configmap