apiVersion: v1
kind: Service
metadata:
  name: els-service
  namespace: "apm"
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: els-configmap
  namespace: apm
data:
  discovery.type: "single-node"
  xpack.security.enabled: "true"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch
  namespace: apm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: "apm"
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-southeast-1a
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          ports:
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: els-configmap
          volumeMounts:
            - name: elsdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elsdata
          persistentVolumeClaim:
            claimName: pvc-elasticsearch