apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: "apm"
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        app: kibana
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.15.2
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-configmap
            items:
              - key: kibana.yml
                path: kibana.yml