apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: apm
data:
  kibana.yml: |
    server.host: "0"
    elasticsearch.hosts: ["http://els-service:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "123456"
    xpack.security.encryptionKey: "e2Cb8DuwvohMJO9GghYbhQI3R0Ad6uv0"
    xpack.security.session.idleTimeout: "1h"
    xpack.security.session.lifespan: "30d"
