apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch
  namespace: apm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi