apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: "apm"
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        app: elasticsearch
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          ports:
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: els-configmap
          volumeMounts:
            - name: elsdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elsdata
          persistentVolumeClaim:
            claimName: pvc-elasticsearch