apiVersion: v1
kind: Service
metadata:
  name: els-service
  namespace: "apm"
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30037
  selector:
    app: elasticsearch