apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
  namespace: apm
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elsdata"