apiVersion: v1
kind: Service
metadata:
  name: apm-service
  namespace: "apm"
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30038
  selector:
    app: apm-server