apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-configmap
  namespace: apm
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      rum:
        enabled: true
    apm-server.kibana:
      host: "kibana-service:5601"
      protocol: "http"
      enabled: true
      username: "elastic"
      password: "123456"
    output.elasticsearch:
      hosts: ["els-service:9200"]
      username: "elastic"
      password: "123456"